project_id = "sphtzpjytpcjutguijtq"

[functions.bank-operations]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false

[functions.scheduled-maintenance]
verify_jwt = false

[functions.generate-report]
verify_jwt = false
